import praw
import json
import time
import os

# === USE ENVIRONMENT VARIABLES FOR SECRETS === #
CLIENT_ID = os.environ["CLIENT_ID"]
CLIENT_SECRET = os.environ["CLIENT_SECRET"]
USERNAME = os.environ["USERNAME"]
PASSWORD = os.environ["PASSWORD"]
USER_AGENT = "OpenHFYBot v1.0 by u/SciFiStories1977"
SUBREDDIT_NAME = "OpenHFY"
BOT_SIGNATURE = "\n\n*This comment was generated by OpenChronicleBot.*"

reddit = praw.Reddit(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    username=USERNAME,
    password=PASSWORD,
    user_agent=USER_AGENT
)

subreddit = reddit.subreddit(SUBREDDIT_NAME)

try:
    with open("processed_posts.json", "r") as f:
        processed_posts = json.load(f)
except FileNotFoundError:
    processed_posts = []

print(f"Listening to new posts in r/{SUBREDDIT_NAME}...")
for submission in subreddit.stream.submissions(skip_existing=True):
    if submission.id in processed_posts:
        continue

    author = submission.author.name
    print(f"New post by u/{author}: {submission.title}")

    history = list(subreddit.search(f"author:{author}", sort="new", limit=5))
    other_posts = [p for p in history if p.id != submission.id]

    if not other_posts:
        continue

    reply = f"u/{author} has posted {len(other_posts)} other story{'ies' if len(other_posts) != 1 else 'y'} in r/{SUBREDDIT_NAME} including:\n\n"
    for p in other_posts[:3]:
        reply += f"- [{p.title}]({p.shortlink})\n"

    reply += BOT_SIGNATURE

    submission.reply(reply)
    print("Replied with user history.")

    processed_posts.append(submission.id)
    with open("processed_posts.json", "w") as f:
        json.dump(processed_posts, f)

    time.sleep(10)
